# config for Travis CI
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - pep8 apps/
  - python manage.py test
